"""
Django settings for ndms project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
#
# =========================================================
# ENVIRONMENT-VARIABLE CONFIGURATION
# =========================================================
#
# Every value below still falls back to the exact same
# development defaults this file already had, so `runserver`
# on a developer machine with NO environment variables set
# behaves identically to before. Nothing here changes local
# dev behavior by itself — these only take effect once the
# corresponding environment variable is actually set (e.g. by
# a real deployment, or by a local .env loaded via
# `python-manage.py` / your process manager / `direnv` /
# `python-dotenv`, none of which this project currently
# requires you to install).
#
# See .env.example at the project root for the full list of
# variables a production deployment must set.
# =========================================================

# SECURITY WARNING: keep the secret key used in production secret!
# This project previously had a real development SECRET_KEY hard-coded
# here as a fallback. That value was already committed to Git history
# (and shared in a ZIP), so it must be treated as permanently exposed
# and MUST NEVER be reused anywhere. It has been removed outright
# rather than replaced with another hard-coded value.
#
# SECRET_KEY is now read ONLY from the environment. You must set
# DJANGO_SECRET_KEY in your local .env before running the server.
# Generate one with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
# Unset/blank DJANGO_DEBUG keeps the original default of True, so
# local development is unaffected. Set DJANGO_DEBUG=False in every
# real deployment.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() == 'true'

# Unset DJANGO_ALLOWED_HOSTS keeps the original hard-coded dev list.
# A real deployment MUST set this to its real domain(s), comma
# separated (e.g. "ndms.example.gov.np,www.ndms.example.gov.np").
_default_allowed_hosts = '127.0.0.1,localhost,192.168.18.106'
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', _default_allowed_hosts
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'reports',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Must run right after AuthenticationMiddleware (needs
    # request.user resolved) and before every other middleware below
    # that assumes an authenticated request.user is still active.
    'reports.middleware.DeactivatedAccountMiddleware',

    'reports.middleware.AdminTimezoneMiddleware',
    'reports.middleware.CitizenTimezoneMiddleware',
    'reports.middleware.AdminCitizenPortalIsolationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ndms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Citizen Settings -> project-wide preferences
                # (date format, time zone). Admin accounts and
                # anonymous visitors receive project defaults.
                'reports.context_processors.citizen_preferences',

                # Disaster unread red-dot indicator -> shared
                # has_unread_disaster_alert value used by the
                # public navbar, Disasters dropdown, and the
                # Dashboard sidebar.
                'reports.context_processors.disaster_alert_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'ndms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (user-uploaded incident photos)
# https://docs.djangoproject.com/en/6.0/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'reports.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# =========================================================
# "REMEMBER ME" SESSION DURATION
# =========================================================
#
# How long a session lasts (in seconds) when the user checks
# "Remember me" on login/register. Falls back to 30 days if
# DJANGO_REMEMBER_ME_SESSION_AGE isn't set, so local dev is
# unaffected. An UNCHECKED "Remember me" gives a browser-session
# cookie (request.session.set_expiry(0) in user_login()/register()
# in reports/views.py), so the user is signed out when the browser
# closes. Only the session id is ever stored -- never the password.
# =========================================================

REMEMBER_ME_SESSION_AGE = int(
    os.environ.get(
        'DJANGO_REMEMBER_ME_SESSION_AGE',
        str(60 * 60 * 24 * 30),  # 30 days
    )
)


# =========================================================
# PRODUCTION-ONLY SECURITY SETTINGS
# =========================================================
#
# Every setting in this block is a no-op in local development
# (DEBUG=True, the default above) and only activates once a real
# deployment sets DJANGO_DEBUG=False. This deliberately does NOT
# force HTTPS/secure-cookie behavior onto `runserver`, which serves
# plain HTTP and would otherwise silently break login (a browser
# will not send a `Secure` cookie back over plain HTTP).
#
# CSRF_TRUSTED_ORIGINS must list the exact scheme+domain(s) real
# users submit forms from, e.g.
#   DJANGO_CSRF_TRUSTED_ORIGINS=https://ndms.example.gov.np
# =========================================================

if not DEBUG:

    SECURE_SSL_REDIRECT = (
        os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True')
        .strip().lower() == 'true'
    )

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True

    SECURE_HSTS_SECONDS = int(
        os.environ.get('DJANGO_HSTS_SECONDS', '31536000')
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get(
            'DJANGO_CSRF_TRUSTED_ORIGINS', ''
        ).split(',')
        if origin.strip()
    ]

    # django-admin/reports own logging still goes to the console
    # (captured by whatever process manager runs the app), but errors
    # are no longer shown to visitors — they get Django's generic
    # 500 page instead, matching what DEBUG=False already does.


# =========================================================
# EMAIL CONFIGURATION
# =========================================================
#
# Password reset (and any other outgoing mail) uses Django's
# console backend by default — this is intentional for local
# development: reset emails print to the runserver terminal
# instead of actually sending, so you never need real SMTP
# credentials just to develop/test the flow. That behavior is
# UNCHANGED here.
#
# To send real email in production, set EMAIL_HOST (and the
# related vars below) in the environment; this switches to
# Django's SMTP backend automatically. Leaving EMAIL_HOST unset
# keeps the console backend even with DEBUG=False, so a
# deployment that hasn't configured mail yet fails safe (visible
# in the server logs) instead of silently pretending to send.
# =========================================================

if os.environ.get('EMAIL_HOST'):

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = (
        os.environ.get('EMAIL_USE_TLS', 'True').strip().lower() == 'true'
    )

else:

    EMAIL_BACKEND = (
        'django.core.mail.backends.console.EmailBackend'
    )

DEFAULT_FROM_EMAIL = os.environ.get(
    'DJANGO_DEFAULT_FROM_EMAIL',
    'NDMS <noreply@ndms.local>'
)


# =========================================================
# GOOGLE MAPS CONFIGURATION
# =========================================================
#
# Used by the Report Incident and Report Detail pages to
# render real Google Maps (Maps JavaScript API), resolve
# addresses (Geocoding API), and power the "Search Google
# Maps" box on Report Incident (Places API).
#
# SETUP:
#   1. Go to https://console.cloud.google.com/google/maps-apis
#   2. Create/select a project and ENABLE:
#        - Maps JavaScript API
#        - Geocoding API
#        - Places API
#      (all three — "map loads but address never fills in" is
#      almost always the Geocoding API not being enabled here;
#      "map loads but the search box finds nothing" is almost
#      always the Places API not being enabled here)
#   3. Go to Billing and confirm a billing account is linked
#      to this project — required by Google Maps Platform even
#      within the free monthly credit. Without it, every
#      Geocoding/Places call fails with REQUEST_DENIED even
#      though the APIs show as "enabled".
#   4. Create an API key and restrict it to:
#        - Application restriction -> Websites:
#              http://127.0.0.1:8000/*
#              http://localhost:8000/*
#          (add your production domain(s) when you deploy)
#        - API restriction:
#              Maps JavaScript API, Geocoding API, Places API
#   5. Paste the key below.
#
# SECURITY:
#   Do not commit a real key to source control. This project loads
#   it ONLY from the GOOGLE_MAPS_API_KEY environment variable — see
#   .env.example. A real key previously lived here as a hard-coded
#   fallback and was already committed to Git history, so it must be
#   treated as permanently exposed: rotate/restrict it in the Google
#   Cloud Console and put the NEW key only in your local .env. With
#   no .env set, GOOGLE_MAPS_API_KEY is now empty and the map simply
#   won't load until you configure it — this is intentional.
#
# =========================================================

GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')