# Generated by Django 6.0.3 on 2026-08-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_disastertype_disasterreport_disaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_type', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
