# Generated by Django 6.0.3 on 2026-08-25 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_emergencyagency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_details', models.TextField()),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disaster_updates', to='reports.emergencyagency')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reports.disaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disaster_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
