# Generated by Django 6.0.3 on 2026-08-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='disaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.disaster'),
        ),
        migrations.AlterField(
            model_name='disastertype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
