# Generated by Django 6.0.3 on 2026-08-28 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterreport',
            name='photo',
        ),
        migrations.CreateModel(
            name='DisasterReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='disaster_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.disasterreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
