# Generated by Django 6.0.3 on 2026-08-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_disasterreport_photo_disasterreportphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disasterreportphoto',
            options={},
        ),
        migrations.RenameField(
            model_name='disasterreportphoto',
            old_name='photo',
            new_name='image',
        ),
    ]
