# Generated by Django 6.0.3 on 2026-08-30 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_disasterreportphoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('NE', 'Nepali')], default='EN', max_length=10)),
                ('time_zone', models.CharField(choices=[('Asia/Kathmandu', 'Nepal Time (Asia/Kathmandu)'), ('Asia/Kolkata', 'India Time (Asia/Kolkata)'), ('Asia/Dhaka', 'Bangladesh Time (Asia/Dhaka)'), ('Asia/Dubai', 'Gulf Time (Asia/Dubai)'), ('UTC', 'Coordinated Universal Time (UTC)'), ('Europe/London', 'UK Time (Europe/London)'), ('America/New_York', 'US Eastern Time (America/New_York)')], default='Asia/Kathmandu', max_length=50)),
                ('date_format', models.CharField(choices=[('DMY', 'DD/MM/YYYY'), ('MDY', 'MM/DD/YYYY'), ('YMD', 'YYYY-MM-DD')], default='DMY', max_length=10)),
                ('dashboard_view', models.CharField(choices=[('SUMMARY', 'Summary View'), ('DETAILED', 'Detailed View')], default='SUMMARY', max_length=10)),
                ('disaster_alerts', models.BooleanField(default=True)),
                ('report_status_updates', models.BooleanField(default=True)),
                ('emergency_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('allow_authority_contact', models.BooleanField(default=True)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('font_size', models.CharField(choices=[('STANDARD', 'Standard'), ('LARGE', 'Large')], default='STANDARD', max_length=10)),
                ('location_permission', models.CharField(choices=[('ALWAYS_ASK', 'Always Ask'), ('ALWAYS_ALLOW', 'Always Allow'), ('NEVER', 'Never Allow')], default='ALWAYS_ASK', max_length=15)),
                ('photo_upload_preference', models.CharField(choices=[('ALWAYS_ASK', 'Always Ask'), ('AUTO_UPLOAD', 'Auto Upload'), ('WIFI_ONLY', 'Wi-Fi Only')], default='ALWAYS_ASK', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.disastertype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]