# Generated by Django 6.0.3 on 2026-09-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('TECHNICAL', 'Technical Issue'), ('REPORT_SUBMISSION', 'Report Submission Issue'), ('NOTIFICATION', 'Notification Issue'), ('ACCOUNT', 'Account Issue'), ('PROFILE', 'Profile Issue'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
