# Generated by Django 6.0.3 on 2026-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_supportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen')], default='CITIZEN', max_length=20),
        ),
    ]