# Generated by Django 6.0.3 on 2026-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_disasterphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
