# Generated by Django 6.0.3 on 2026-09-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_alter_disasterphoto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('LIGHT', 'Light'), ('DARK', 'Dark')], default='SYSTEM', max_length=10),
        ),
    ]
